[package]
name = "blurhash-fast"
description = "blurhash"
readme = "README.md"
version = "0.1.0"
authors = ["Kenan Sulayman <kenan@styla.com>"]
license-file = "license"
edition = "2018"

[dev-dependencies]
image = "0.23.14"

[dependencies]
rayon = "1.5.1"
